import type { BlogArticle } from './types'
import { content as contentWws } from './content/ws-puntentelling-2026'
import { content as contentWetBetaalbareHuur } from './content/wet-betaalbare-huur-gids'
import { content as contentHuurverhoging } from './content/huurverhogingsregels-2026'
import { content as contentEnergielabel } from './content/energielabel-verplichtingen-verhuurders'
import { content as contentGoedVerhuurderschap } from './content/wet-goed-verhuurderschap'

const articles: BlogArticle[] = [
  {
    slug: 'ws-puntentelling-2026',
    title: 'WWS Puntentelling 2026 — Alles Wat Je Moet Weten',
    summary: 'Hoe het Woningwaarderingsstelsel werkt, alle puntencategorieën, WOZ 2026, liberalisatiegrens 187 punten en verplichte puntentelling bij elk nieuw contract.',
    category: 'wetgeving-compliance',
    tags: ['WWS', 'puntentelling', '2026', 'liberalisatiegrens'],
    content: contentWws,
    publishDate: '2025-12-01',
    lastUpdated: '2026-01-15',
    readingTime: 6,
    featured: true,
    relatedArticles: ['wet-betaalbare-huur-gids', 'huurverhogingsregels-2026', 'energielabel-verplichtingen-verhuurders'],
  },
  {
    slug: 'wet-betaalbare-huur-gids',
    title: 'Wet Betaalbare Huur — Complete Gids voor Verhuurders',
    summary: 'Wat de wet inhoudt, drie sectoren (sociaal/midden/vrij), verplichte puntentelling, overgangsbepalingen, Huurcommissie en boetes tot €103.000.',
    category: 'wetgeving-compliance',
    tags: ['Wet Betaalbare Huur', 'WWS', 'sociaal', 'midden', 'vrije sector'],
    content: contentWetBetaalbareHuur,
    publishDate: '2025-11-15',
    lastUpdated: '2026-01-10',
    readingTime: 5,
    featured: false,
    relatedArticles: ['ws-puntentelling-2026', 'huurverhogingsregels-2026', 'wet-goed-verhuurderschap'],
  },
  {
    slug: 'huurverhogingsregels-2026',
    title: 'Huurverhogingsregels 2026 — Per Sector Uitgelegd',
    summary: 'Maximale verhoging sociale (4,1%), midden (6,1%) en vrije sector (4,4%). Wanneer doorvoeren, inkomensafhankelijke verhoging en procedure.',
    category: 'wetgeving-compliance',
    tags: ['huurverhoging', 'indexatie', '2026', 'sociaal', 'midden', 'vrije sector'],
    content: contentHuurverhoging,
    publishDate: '2025-12-10',
    lastUpdated: '2026-01-01',
    readingTime: 4,
    featured: false,
    relatedArticles: ['ws-puntentelling-2026', 'wet-betaalbare-huur-gids', 'huurindexatie-automatiseren'],
  },
  {
    slug: 'energielabel-verplichtingen-verhuurders',
    title: 'Energielabel Verplichtingen voor Verhuurders — Tijdlijn tot 2030',
    summary: 'Labelplicht bij verhuur, nieuwe methodiek 2026, minimaal label D in 2029, nieuwe indeling A–G in 2030. Gevolgen voor WWS.',
    category: 'verduurzaming-energie',
    tags: ['energielabel', 'verduurzaming', '2030', 'label D'],
    content: contentEnergielabel,
    publishDate: '2025-11-20',
    lastUpdated: '2026-01-05',
    readingTime: 5,
    featured: false,
    relatedArticles: ['ws-puntentelling-2026', 'verduurzaming-huurwoningen-subsidies', 'zonnepanelen-huurwoningen'],
  },
  {
    slug: 'wet-goed-verhuurderschap',
    title: 'Wet Goed Verhuurderschap — Wat Moet Je Weten?',
    summary: 'De 6 basisregels: niet discrimineren, niet intimideren, waarborgsom max 2x kale huur, schriftelijk contract, informatieplicht, servicekosten. Handhaving en boetes.',
    category: 'wetgeving-compliance',
    tags: ['Wet Goed Verhuurderschap', 'meldpunt', 'handhaving', 'boetes'],
    content: contentGoedVerhuurderschap,
    publishDate: '2025-10-01',
    lastUpdated: '2025-12-20',
    readingTime: 5,
    featured: false,
    relatedArticles: ['wet-betaalbare-huur-gids', 'huurcontracten-soorten-valkuilen', 'huurdersscreening-selectie'],
  },
  // Placeholder artikelen
  {
    slug: 'servicekosten-regels-afrekening',
    title: 'Servicekosten — Regels, Afrekening en Valkuilen',
    summary: 'Wat servicekosten zijn, verschil kale en all-in huur, jaarlijkse afrekening, redelijkheidsvereiste en rol Huurcommissie.',
    category: 'wetgeving-compliance',
    tags: ['servicekosten', 'afrekening', 'Huurcommissie'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-09-01',
    lastUpdated: '2025-09-01',
    readingTime: 4,
    featured: false,
    relatedArticles: ['wet-goed-verhuurderschap', 'huurcontracten-soorten-valkuilen'],
    placeholder: true,
  },
  {
    slug: 'rendement-berekenen-vastgoed',
    title: 'Rendement Berekenen op Vastgoed — BAR, NAR en Cashflow',
    summary: 'Bruto en netto aanvangsrendement, cashflow, break-even en veelgemaakte fouten. Met rekenvoorbeeld en impact box 3.',
    category: 'financieel-beheer',
    tags: ['rendement', 'BAR', 'NAR', 'cashflow'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-08-15',
    lastUpdated: '2025-08-15',
    readingTime: 6,
    featured: false,
    relatedArticles: ['belastingen-vastgoedbeleggers-2026', 'facturatie-betalingsverkeer'],
    placeholder: true,
  },
  {
    slug: 'huurindexatie-automatiseren',
    title: 'Huurindexatie — Automatiseren en Correct Doorvoeren',
    summary: 'Wettelijke basis, CBS-index, berekening, timing en communicatie. Automatisering via vastgoedsoftware.',
    category: 'financieel-beheer',
    tags: ['indexatie', 'huurverhoging', 'CBS'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-08-01',
    lastUpdated: '2025-08-01',
    readingTime: 4,
    featured: false,
    relatedArticles: ['huurverhogingsregels-2026', 'facturatie-betalingsverkeer'],
    placeholder: true,
  },
  {
    slug: 'belastingen-vastgoedbeleggers-2026',
    title: 'Belastingen voor Vastgoedbeleggers — Box 3 in 2026',
    summary: 'Box 3, overdrachtsbelasting 10,4%, vrijstelling 18-35 jaar tot €555.000, hypotheekrenteaftrek 37,56%. VvB-structuur.',
    category: 'financieel-beheer',
    tags: ['box 3', 'belasting', 'overdrachtsbelasting', 'VvB'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-07-15',
    lastUpdated: '2025-07-15',
    readingTime: 5,
    featured: false,
    relatedArticles: ['rendement-berekenen-vastgoed', 'facturatie-betalingsverkeer'],
    placeholder: true,
  },
  {
    slug: 'facturatie-betalingsverkeer',
    title: 'Facturatie en Betalingsverkeer voor Verhuurders',
    summary: 'Huurincasso, aanmaningsprocedure, Wki, automatisering en bankimport.',
    category: 'financieel-beheer',
    tags: ['facturatie', 'incasso', 'Wki', 'MT940'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-07-01',
    lastUpdated: '2025-07-01',
    readingTime: 4,
    featured: false,
    relatedArticles: ['huurindexatie-automatiseren', 'rendement-berekenen-vastgoed'],
    placeholder: true,
  },
  {
    slug: 'verduurzaming-huurwoningen-subsidies',
    title: 'Verduurzaming van Huurwoningen — Kansen en Subsidies',
    summary: 'SVOH tot €15.000, ISDE, maatregelen met meeste impact, kosten-baten en terugverdientijd.',
    category: 'verduurzaming-energie',
    tags: ['verduurzaming', 'SVOH', 'ISDE', 'subsidie'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-06-15',
    lastUpdated: '2025-06-15',
    readingTime: 5,
    featured: false,
    relatedArticles: ['energielabel-verplichtingen-verhuurders', 'zonnepanelen-huurwoningen'],
    placeholder: true,
  },
  {
    slug: 'zonnepanelen-huurwoningen',
    title: 'Zonnepanelen op Huurwoningen — Regelgeving en Mogelijkheden',
    summary: 'Saldering, eigenaarschap, impact op label en WWS, VvE en financiering.',
    category: 'verduurzaming-energie',
    tags: ['zonnepanelen', 'saldering', 'energielabel'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-06-01',
    lastUpdated: '2025-06-01',
    readingTime: 4,
    featured: false,
    relatedArticles: ['energielabel-verplichtingen-verhuurders', 'verduurzaming-huurwoningen-subsidies'],
    placeholder: true,
  },
  {
    slug: 'mjop-meerjarenonderhoudsplan',
    title: 'Meerjarenonderhoudsplan (MJOP) — Complete Handleiding',
    summary: 'Wat een MJOP is, drie kernonderdelen, reservefonds 0,5%, DMJOP, conditiemeting NEN 2767 en valkuilen.',
    category: 'onderhoud-inspecties',
    tags: ['MJOP', 'reservefonds', 'VvE', 'onderhoud'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-05-15',
    lastUpdated: '2025-05-15',
    readingTime: 6,
    featured: false,
    relatedArticles: ['onderhoud-uitbesteden', 'vve-financien'],
    placeholder: true,
  },
  {
    slug: 'onderhoud-uitbesteden',
    title: 'Onderhoud Uitbesteden of Zelf Doen? — Tips voor Verhuurders',
    summary: 'Klein vs groot onderhoud, wettelijke verplichtingen, preventief vs correctief en documentatie.',
    category: 'onderhoud-inspecties',
    tags: ['onderhoud', 'verhuurder', 'storingsmeldingen'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-05-01',
    lastUpdated: '2025-05-01',
    readingTime: 4,
    featured: false,
    relatedArticles: ['mjop-meerjarenonderhoudsplan', 'begin-eindinspecties'],
    placeholder: true,
  },
  {
    slug: 'brandveiligheid-huurwoningen-2026',
    title: 'Brandveiligheid in Huurwoningen — Verplichtingen 2026',
    summary: 'Rookmelders, vluchtwegen, verantwoordelijkheid en VvE.',
    category: 'onderhoud-inspecties',
    tags: ['brandveiligheid', 'rookmelders', 'Bouwbesluit'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-04-15',
    lastUpdated: '2025-04-15',
    readingTime: 3,
    featured: false,
    relatedArticles: ['onderhoud-uitbesteden', 'begin-eindinspecties'],
    placeholder: true,
  },
  {
    slug: 'begin-eindinspecties',
    title: 'Begin- en Eindinspecties — Zo Doe Je Het Goed',
    summary: 'Waarom inspecties, wat vastleggen, digitaal rapport en normale slijtage vs schade.',
    category: 'onderhoud-inspecties',
    tags: ['inspectie', 'waarborgsom', 'schade'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-04-01',
    lastUpdated: '2025-04-01',
    readingTime: 4,
    featured: false,
    relatedArticles: ['onderhoud-uitbesteden', 'huurcontracten-soorten-valkuilen'],
    placeholder: true,
  },
  {
    slug: 'huurdersscreening-selectie',
    title: 'Huurdersscreening — Selectieprocedure Volgens de Wet',
    summary: 'Objectieve criteria, wat je wel en niet mag vragen, BKR, Rotterdam-wet en documentatie.',
    category: 'huurdersbeheer',
    tags: ['screening', 'selectie', 'Wet Goed Verhuurderschap'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-03-15',
    lastUpdated: '2025-03-15',
    readingTime: 4,
    featured: false,
    relatedArticles: ['wet-goed-verhuurderschap', 'huurcontracten-soorten-valkuilen'],
    placeholder: true,
  },
  {
    slug: 'huurcontracten-soorten-valkuilen',
    title: 'Huurcontracten — Soorten, Looptijd en Valkuilen',
    summary: 'Onbepaalde vs tijdelijke tijd, verplichte bijlagen (puntentelling, energielabel), waarborgsom en opzegging.',
    category: 'huurdersbeheer',
    tags: ['huurcontract', 'puntentelling', 'waarborgsom'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-03-01',
    lastUpdated: '2025-03-01',
    readingTime: 5,
    featured: false,
    relatedArticles: ['wet-goed-verhuurderschap', 'huurdersscreening-selectie', 'communicatie-huurders'],
    placeholder: true,
  },
  {
    slug: 'communicatie-huurders',
    title: 'Communicatie met Huurders — Best Practices',
    summary: 'Huurdersportaal, storingsmeldingen, huurverhogingsbrief en conflicthantering.',
    category: 'huurdersbeheer',
    tags: ['communicatie', 'huurdersportaal', 'storingsmeldingen'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-02-15',
    lastUpdated: '2025-02-15',
    readingTime: 4,
    featured: false,
    relatedArticles: ['huurcontracten-soorten-valkuilen', 'onderhoud-uitbesteden'],
    placeholder: true,
  },
  {
    slug: 'vve-beheer-gids',
    title: 'VvE-Beheer — Complete Gids voor Bestuurders',
    summary: 'Wat een VvE is, rollen, reservefonds, vergaderingen en professioneel beheer.',
    category: 'vve-beheer',
    tags: ['VvE', 'bestuur', 'reservefonds'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-02-01',
    lastUpdated: '2025-02-01',
    readingTime: 5,
    featured: false,
    relatedArticles: ['vve-financien', 'vve-verduurzaming'],
    placeholder: true,
  },
  {
    slug: 'vve-financien',
    title: 'VvE-Financiën — Begroting, Reservefonds en Bijdrage',
    summary: 'Jaarlijkse begroting, breukdelen, reservefonds 0,5%, jaarrekening en achterstanden.',
    category: 'vve-beheer',
    tags: ['VvE', 'financien', 'reservefonds', 'begroting'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-01-15',
    lastUpdated: '2025-01-15',
    readingTime: 5,
    featured: false,
    relatedArticles: ['vve-beheer-gids', 'mjop-meerjarenonderhoudsplan'],
    placeholder: true,
  },
  {
    slug: 'vve-verduurzaming',
    title: 'VvE en Verduurzaming — Besluitvorming en Financiering',
    summary: 'Gewone vs gekwalificeerde meerderheid, VvE Energiebespaarlening, subsidies en DMJOP.',
    category: 'vve-beheer',
    tags: ['VvE', 'verduurzaming', 'subsidie'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-01-01',
    lastUpdated: '2025-01-01',
    readingTime: 4,
    featured: false,
    relatedArticles: ['vve-beheer-gids', 'verduurzaming-huurwoningen-subsidies'],
    placeholder: true,
  },
  {
    slug: 'vastgoedmarkt-2026',
    title: 'Nederlandse Vastgoedmarkt 2026 — Trends en Vooruitzichten',
    summary: 'Woningtekort, prijsontwikkeling, impact Wet Betaalbare Huur en institutionele vs particuliere beleggers.',
    category: 'markt-trends',
    tags: ['vastgoedmarkt', '2026', 'trends'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-12-20',
    lastUpdated: '2025-12-20',
    readingTime: 5,
    featured: false,
    relatedArticles: ['proptech-digitalisering'],
    placeholder: true,
  },
  {
    slug: 'proptech-digitalisering',
    title: 'PropTech en Digitalisering in Vastgoedbeheer',
    summary: 'AI, slimme meters, huurdersportalen, automatisering en waar op letten bij vastgoedsoftware.',
    category: 'markt-trends',
    tags: ['PropTech', 'digitalisering', 'AI'],
    content: '*Dit artikel wordt binnenkort gepubliceerd.*',
    publishDate: '2025-12-15',
    lastUpdated: '2025-12-15',
    readingTime: 4,
    featured: false,
    relatedArticles: ['vastgoedmarkt-2026', 'communicatie-huurders'],
    placeholder: true,
  },
]

export function getAllArticles(): BlogArticle[] {
  return articles
}
